/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAccountsRouteImport } from './routes/_app/accounts'
import { Route as AppAuditRouteImport } from './routes/_app/audit'
import { Route as AppCardsRouteImport } from './routes/_app/cards'
import { Route as AppComplianceRouteImport } from './routes/_app/compliance'
import { Route as AppCustomersRouteImport } from './routes/_app/customers'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppRiskRouteImport } from './routes/_app/risk'
import { Route as AppRolesRouteImport } from './routes/_app/roles'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSupportRouteImport } from './routes/_app/support'
import { Route as AppTransactionsRouteImport } from './routes/_app/transactions'
import { Route as AppTransfersRouteImport } from './routes/_app/transfers'
import { Route as AppTreasuryRouteImport } from './routes/_app/treasury'
import { Route as AppUsersRouteImport } from './routes/_app/users'
import { Route as AppAccountsIdRouteImport } from './routes/_app/accounts.$id'
import { Route as AppCustomersIdRouteImport } from './routes/_app/customers.$id'
import { Route as AppTransactionsIdRouteImport } from './routes/_app/transactions.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsRoute = AppAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppCardsRoute = AppCardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => AppRoute,
} as any)
const AppComplianceRoute = AppComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppRiskRoute = AppRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => AppRoute,
} as any)
const AppRolesRoute = AppRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportRoute = AppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionsRoute = AppTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppRoute,
} as any)
const AppTransfersRoute = AppTransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => AppRoute,
} as any)
const AppTreasuryRoute = AppTreasuryRouteImport.update({
  id: '/treasury',
  path: '/treasury',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsIdRoute = AppAccountsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppAccountsRoute,
} as any)
const AppCustomersIdRoute = AppCustomersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppCustomersRoute,
} as any)
const AppTransactionsIdRoute = AppTransactionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppTransactionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/accounts': typeof AppAccountsRouteWithChildren
  '/audit': typeof AppAuditRoute
  '/cards': typeof AppCardsRoute
  '/compliance': typeof AppComplianceRoute
  '/customers': typeof AppCustomersRouteWithChildren
  '/notifications': typeof AppNotificationsRoute
  '/reports': typeof AppReportsRoute
  '/risk': typeof AppRiskRoute
  '/roles': typeof AppRolesRoute
  '/settings': typeof AppSettingsRoute
  '/support': typeof AppSupportRoute
  '/transactions': typeof AppTransactionsRouteWithChildren
  '/transfers': typeof AppTransfersRoute
  '/treasury': typeof AppTreasuryRoute
  '/users': typeof AppUsersRoute
  '/accounts/$id': typeof AppAccountsIdRoute
  '/customers/$id': typeof AppCustomersIdRoute
  '/transactions/$id': typeof AppTransactionsIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/accounts': typeof AppAccountsRouteWithChildren
  '/audit': typeof AppAuditRoute
  '/cards': typeof AppCardsRoute
  '/compliance': typeof AppComplianceRoute
  '/customers': typeof AppCustomersRouteWithChildren
  '/notifications': typeof AppNotificationsRoute
  '/reports': typeof AppReportsRoute
  '/risk': typeof AppRiskRoute
  '/roles': typeof AppRolesRoute
  '/settings': typeof AppSettingsRoute
  '/support': typeof AppSupportRoute
  '/transactions': typeof AppTransactionsRouteWithChildren
  '/transfers': typeof AppTransfersRoute
  '/treasury': typeof AppTreasuryRoute
  '/users': typeof AppUsersRoute
  '/': typeof AppIndexRoute
  '/accounts/$id': typeof AppAccountsIdRoute
  '/customers/$id': typeof AppCustomersIdRoute
  '/transactions/$id': typeof AppTransactionsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/accounts': typeof AppAccountsRouteWithChildren
  '/_app/audit': typeof AppAuditRoute
  '/_app/cards': typeof AppCardsRoute
  '/_app/compliance': typeof AppComplianceRoute
  '/_app/customers': typeof AppCustomersRouteWithChildren
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/risk': typeof AppRiskRoute
  '/_app/roles': typeof AppRolesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/support': typeof AppSupportRoute
  '/_app/transactions': typeof AppTransactionsRouteWithChildren
  '/_app/transfers': typeof AppTransfersRoute
  '/_app/treasury': typeof AppTreasuryRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/': typeof AppIndexRoute
  '/_app/accounts/$id': typeof AppAccountsIdRoute
  '/_app/customers/$id': typeof AppCustomersIdRoute
  '/_app/transactions/$id': typeof AppTransactionsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/accounts'
    | '/audit'
    | '/cards'
    | '/compliance'
    | '/customers'
    | '/notifications'
    | '/reports'
    | '/risk'
    | '/roles'
    | '/settings'
    | '/support'
    | '/transactions'
    | '/transfers'
    | '/treasury'
    | '/users'
    | '/accounts/$id'
    | '/customers/$id'
    | '/transactions/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/accounts'
    | '/audit'
    | '/cards'
    | '/compliance'
    | '/customers'
    | '/notifications'
    | '/reports'
    | '/risk'
    | '/roles'
    | '/settings'
    | '/support'
    | '/transactions'
    | '/transfers'
    | '/treasury'
    | '/users'
    | '/'
    | '/accounts/$id'
    | '/customers/$id'
    | '/transactions/$id'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/accounts'
    | '/_app/audit'
    | '/_app/cards'
    | '/_app/compliance'
    | '/_app/customers'
    | '/_app/notifications'
    | '/_app/reports'
    | '/_app/risk'
    | '/_app/roles'
    | '/_app/settings'
    | '/_app/support'
    | '/_app/transactions'
    | '/_app/transfers'
    | '/_app/treasury'
    | '/_app/users'
    | '/_app/'
    | '/_app/accounts/$id'
    | '/_app/customers/$id'
    | '/_app/transactions/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts': {
      id: '/_app/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AppAccountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cards': {
      id: '/_app/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof AppCardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/compliance': {
      id: '/_app/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof AppComplianceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers': {
      id: '/_app/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/risk': {
      id: '/_app/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof AppRiskRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/roles': {
      id: '/_app/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AppRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/support': {
      id: '/_app/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AppSupportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transactions': {
      id: '/_app/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AppTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transfers': {
      id: '/_app/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof AppTransfersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/treasury': {
      id: '/_app/treasury'
      path: '/treasury'
      fullPath: '/treasury'
      preLoaderRoute: typeof AppTreasuryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts/$id': {
      id: '/_app/accounts/$id'
      path: '/$id'
      fullPath: '/accounts/$id'
      preLoaderRoute: typeof AppAccountsIdRouteImport
      parentRoute: typeof AppAccountsRoute
    }
    '/_app/customers/$id': {
      id: '/_app/customers/$id'
      path: '/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof AppCustomersIdRouteImport
      parentRoute: typeof AppCustomersRoute
    }
    '/_app/transactions/$id': {
      id: '/_app/transactions/$id'
      path: '/$id'
      fullPath: '/transactions/$id'
      preLoaderRoute: typeof AppTransactionsIdRouteImport
      parentRoute: typeof AppTransactionsRoute
    }
  }
}

interface AppAccountsRouteChildren {
  AppAccountsIdRoute: typeof AppAccountsIdRoute
}

const AppAccountsRouteChildren: AppAccountsRouteChildren = {
  AppAccountsIdRoute: AppAccountsIdRoute,
}

const AppAccountsRouteWithChildren = AppAccountsRoute._addFileChildren(
  AppAccountsRouteChildren,
)

interface AppCustomersRouteChildren {
  AppCustomersIdRoute: typeof AppCustomersIdRoute
}

const AppCustomersRouteChildren: AppCustomersRouteChildren = {
  AppCustomersIdRoute: AppCustomersIdRoute,
}

const AppCustomersRouteWithChildren = AppCustomersRoute._addFileChildren(
  AppCustomersRouteChildren,
)

interface AppTransactionsRouteChildren {
  AppTransactionsIdRoute: typeof AppTransactionsIdRoute
}

const AppTransactionsRouteChildren: AppTransactionsRouteChildren = {
  AppTransactionsIdRoute: AppTransactionsIdRoute,
}

const AppTransactionsRouteWithChildren = AppTransactionsRoute._addFileChildren(
  AppTransactionsRouteChildren,
)

interface AppRouteChildren {
  AppAccountsRoute: typeof AppAccountsRouteWithChildren
  AppAuditRoute: typeof AppAuditRoute
  AppCardsRoute: typeof AppCardsRoute
  AppComplianceRoute: typeof AppComplianceRoute
  AppCustomersRoute: typeof AppCustomersRouteWithChildren
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppRiskRoute: typeof AppRiskRoute
  AppRolesRoute: typeof AppRolesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSupportRoute: typeof AppSupportRoute
  AppTransactionsRoute: typeof AppTransactionsRouteWithChildren
  AppTransfersRoute: typeof AppTransfersRoute
  AppTreasuryRoute: typeof AppTreasuryRoute
  AppUsersRoute: typeof AppUsersRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountsRoute: AppAccountsRouteWithChildren,
  AppAuditRoute: AppAuditRoute,
  AppCardsRoute: AppCardsRoute,
  AppComplianceRoute: AppComplianceRoute,
  AppCustomersRoute: AppCustomersRouteWithChildren,
  AppNotificationsRoute: AppNotificationsRoute,
  AppReportsRoute: AppReportsRoute,
  AppRiskRoute: AppRiskRoute,
  AppRolesRoute: AppRolesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSupportRoute: AppSupportRoute,
  AppTransactionsRoute: AppTransactionsRouteWithChildren,
  AppTransfersRoute: AppTransfersRoute,
  AppTreasuryRoute: AppTreasuryRoute,
  AppUsersRoute: AppUsersRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
